### ISSUE TITLE
Unity Import

### ISSUE THREAD

**Issue by florolf1** [petrbroz/forge-convert-utils#21] opened 2020-02-24 15:16 UTC
when i import the .gltf models into Unity i get a problem with rendering the models in the editor and on the device.
![Bildschirmfoto 2020-02-24 um 13 19 17](https://user-images.githubusercontent.com/29608141/75164245-ca21bc80-5720-11ea-9d91-bb9302e92fd8.png)
![Bildschirmfoto 2020-02-24 um 13 20 33](https://user-images.githubusercontent.com/29608141/75164246-cc841680-5720-11ea-9754-e2ec8ec1fef5.png)

Every imported material is displayed as transparent.
I have tested three other GLTF Importer and it was the same for all of them.

is there a possibility to change this when converting it from .svf to .gltf?
If not, how did you solve the problem?

To import into Unity I used this plugin: 
https://github.com/Siccity/GLTFUtility

**Comment by petrbroz** [comment] 2020-02-25 09:12
Thank you for reporting the issue @florolf1! Looking at the screenshots, it seems that the objects are visible but rendered out of order (in the first screenshot, the red roof can be seen behind the ground mesh). I'll look into that.

**Comment by florolf1** [comment] 2020-02-25 09:21
Yes, you are right. The problem has to do with how unity render transparent objects.
https://answers.unity.com/questions/609021/how-to-fix-transparent-rendering-problem.html

Changing the render queue for individual objects can fix this, but this wont work if you do this for all objects.
What I wonder is why unity recognizes all materials as transparent, even those which should not be transparent (e.g. roof, walls, etc.) and if there is a possibility to fix this during the converting process.

**Comment by petrbroz** [comment] 2020-02-25 09:51
It's possible that I'm setting the glTF material props incorrectly, causing Unity to think that they're transparent. I'll investigate that area. Thanks for the info!

**Comment by petrbroz** [comment] 2020-02-25 10:16
The issue is now fixed in _develop_ branch and will go live with the next version update.

**Closed** 2020-02-25 10:15 UTC
Labels: bug

**Comment by florolf1** [comment] 2020-02-25 10:31
Tested and it works perfectly.
Thank you!
