### ISSUE TITLE
Transformation missing for xFormType = 4

### ISSUE THREAD

**Issue by rstancioiu** [petrbroz/forge-convert-utils#17] opened 2019-12-19 14:24 UTC
Hello,

I've seen that in some svf projects xFormType of transformation is equal to 4, which is really strange. Also in these projects the objects seem slightly translated depending on the value that is not read. I suppose that it has also an impact on the read of the bounding box and database Id.
Do you have any knowledge about this corresponding transformation ?

Many thanks,
Razvan

**Comment by petrbroz** [comment] 2019-12-20 08:10
Hi Razvan,

Type 4 represents an identity transformation, meaning that the particular fragment is not transformed in any way. In the SVF reader we're skipping this value (storing `null` instead of an actual identity matrix), but it should have no effect on object placement, bounding box, or dbIDs.

Could you provide a sample file where the "slightly translated objects" could be reproduced?

**Comment by petrbroz** [comment] 2020-03-17 09:09
Closing the issue for now since there's been no additional feedback. If there's still an issue with identity xform, we'll reopen it.

**Closed by petrbroz** 2020-03-17 09:09 UTC
Labels: question
